language: node_js

node_js:
  - 10.14.1

cache:
  bundler: true
  yarn: true
  directories:
      - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_95f09924c9e9_key -iv $encrypted_95f09924c9e9_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod -r 600 ~/.ssh
  - echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install

script:
  - yarn run test

deploy:
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/mahoo && git pull' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/mahoo && yarn' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/mahoo && pm2 startOrRestart pm2.config.js --env=production'
    on:
      branch: master
